deployment:
  name: java-deployment
  namespace: dev
  replicaCount: 1

image:
  repository: pranavpk24/javaapp_k8s:26
  pullPolicy: Always
  containerName: javawebapp
  imagePullSecrets: dockerhub
  containerPort: 80

service:
  type: ClusterIP
  clusterIPPort: 80
  targetPort: 8080
